### ISSUE TITLE
Usage with Nuxt

### ISSUE THREAD

**Issue by z3to** [probil/vue-socket.io-extended#182]
Thanks so much for the library! It looks very promising. Unfortunately, I can’t get this running with Nuxt. This is what my store looks like:

```js
import Vue from 'vue'
import Vuex from 'vuex'
import VueSocketio from 'vue-socket.io-extended'
import io from 'socket.io-client'

Vue.use(Vuex)

const store = () => new Vuex.Store({
  state: {
    connect: false,
    message: null
  },
  mutations: {
    SOCKET_CONNECT (state, status) {
      console.log('mutations: SOCKET_CONNECT')
      state.connect = true
    },
    SOCKET_USER_MESSAGE (state, message) {
      console.log('mutations: SOCKET_USER_MESSAGE')
      state.message = message
    }
  },
  actions: {
    socket_userMessage (context, message) {
      console.log('Action: socket_userMessage')
    }
  }
})

Vue.use(VueSocketio, io('http://localhost:8080'), { store })

export default store
```

Whenever I open the website it crashes with this message:
```
project/node_modules/vue-socket.io-extended/dist/vue-socket.io-ext.min.js:1
(function (exports, require, module, __filename, __dirname) { !function(t,e){"object"==typeof exports&&"undefined"!=typeof module?module.exports=e():"function"==typeof define&&define.amd?define(e):t.VueSocketIOExt=e()}(this,function(){"use strict";var t=function(t){return"function"==typeof t},e=function(){for(var t=arguments.length,e=Array(t),n=0;n<t;n++)e[n]=arguments[n];return function(t){return e.reduce(function(t,e){return e(t)},t)}},n=function(t){return function(e){return t+e}},r=function(t,e){if(!(t instanceof e))throw new TypeError("Cannot call a class as a function")},o=function(){function t(t,e){for(var n=0;n<e.length;n++){var r=e[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(t,r.key,r)}}return function(e,n,r){return n&&t(e.prototype,n),r&&t(e,r),e}}(),i=Object.assign||function(t){for(var e=1;e<arguments.length;e++){var n=arguments[e];for(var r 

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at t.value (project/node_modules/vue-socket.io-extended/dist/vue-socket.io-ext.min.js:1:4003)
    at Socket.<anonymous> (project/node_modules/vue-socket.io-extended/dist/vue-socket.io-ext.min.js:1:3687)
    at Socket.Emitter.emit (project/node_modules/socket.io-client/node_modules/component-emitter/index.js:131:20)
    at Socket.emit (project/node_modules/socket.io-client/lib/socket.js:136:10)
    at Manager.emitAll (project/node_modules/socket.io-client/lib/manager.js:81:27)
    at Socket.<anonymous> (project/node_modules/socket.io-client/lib/manager.js:230:10)
    at Socket.Emitter.emit (project/node_modules/engine.io-client/node_modules/component-emitter/index.js:134:20)
    at Socket.onError (project/node_modules/engine.io-client/lib/socket.js:673:8)
    at XHR.<anonymous> (project/node_modules/engine.io-client/lib/socket.js:264:10)
    at XHR.Emitter.emit (project/node_modules/engine.io-client/node_modules/component-emitter/index.js:134:20)
    at XHR.Transport.onError (project/node_modules/engine.io-client/lib/transport.js:65:8)
    at Request.<anonymous> (project/node_modules/engine.io-client/lib/transports/polling-xhr.js:127:10)
    at Request.Emitter.emit (project/node_modules/engine.io-client/node_modules/component-emitter/index.js:134:20)
    at Request.onError (project/node_modules/engine.io-client/lib/transports/polling-xhr.js:300:8)
    at Timeout._onTimeout (project/node_modules/engine.io-client/lib/transports/polling-xhr.js:247:18)
```

I’m not sure if that is connected in any way, but I would be grateful for any help.

EDIT: It does work without the store inside a component.

**Comment by probil** [comment]
Hi, @z3to 
Thanks for your feedback. 

There is no support for `Nuxt.js` yet. But I'd like to have it. I will investigate your issue soon. :sunglasses: 

Contribution is welcome. If you have any ideas how it can be fixed I will be glad to review & merge it.

**Comment by ll931217** [comment]
Hey @z3to, I got mine to work on `Nuxt.js`. This is how I did it:
### 1. Create a plugin
```javascript
import Vue from 'vue'
import io from 'socket.io-client'
import VueSocketIO from 'vue-socket.io-extended'

export default ({ store }) => {
  Vue.use(VueSocketIO, io('http://localhost:3000'), { store })
}
```
### 2. Add it to your `nuxt.config.js` file
```javascript
module.exports = {
  ...,
  plugins: [
    { src: '~/plugins/socket.io.js', ssr: false }
  ]
}
```
### 3. Setup your server just like a normal socket.io web app.

**Comment by probil** [comment]
Thanks @ll931217 
I will add that to the README

**Comment by probil** [comment]
Added to the [documentation](https://github.com/probil/vue-socket.io-extended#mountain_bicyclist-usage-with-nuxtjs)
